package com.huihe.boyueentities.protocol.home

data class HouseCreateUserRep(

    private val bargainPriceUser: String? = null,
    private val building: String? = null,
    private val buyPrice: String? = null,
    private val changePrice: String? = null,
    private val characteristic: String? = null,
    private val coverImage: String? = null,
    private val createTime: String? = null,
    private val createUser: String? = null,
    private val createUserName: String? = null,
    private val decorat: String? = null,
    private val floor: String? = null,
    private val floorage: String? = null,
    private val hFlag: String? = null,
    private val hNum: String? = null,
    private val hShape: String? = null,
    private val houseCode: String? = null,
    private val houseHolds: String? = null,
    private val housePropertyYear: String? = null,
    private val id: String? = null,
    private val imagUrl: String? = null,
    private val imageUser: String? = null,
    private val isCirculation: String? = null,
    private val isOnlyHouse: String? = null,
    private val label: String? = null,
    private val latestFollowTime: String? = null,
    private val loanState: String? = null,
    private val maintainUser: String? = null,
    private val openTime: String? = null,
    private val openUser: String? = null,
    private val orientation: String? = null,
    private val ownerLowPrice: String? = null,
    private val ownerName: String? = null,
    private val ownerTel: String? = null,
    private val price: String? = null,
    private val propertyRightUserSize: String? = null,
    private val referUrl: String? = null,
    private val remarks: String? = null,
    private val rent: String? = null,
    private val roomNum: String? = null,
    private val seeTime: String? = null,
    private val soldReason: String? = null,
    private val stairs: String? = null,
    private val totalFloor: String? = null,
    private val transactionType: String? = null,
    private val unit: String? = null,
    private val unitPrice: String? = null,
    private val updateTime: String? = null,
    private val updateUser: String? = null,
    private val updateUserName: String? = null,
    private val villageId: String? = null

)
