package com.huihe.boyueentities.protocol.user
//"accompanyImgList": [],
//"accompanyImgUrl": null,
//"accompanyPositionLatitude": null,
//"accompanyPositionLongitude": null,
//"accompanySignInStatus": 0,
//"accompanySignTime": null,
//"accompanyUser": null,
//"accompanyUserId": "b47645c6c9144a0db608d5356c933988",
//"building": "58",
//"hNum": "0802",
//"houseCode": "FY-20-79798",
//"houseId": 102683,
//"id": 24,
//"latitude": "31.29855846573197",
//"longitude": "121.4111697324239",
//"takeImgList": [],
//"takeImgUrl": null,
//"takeLookTaskId": "12",
//"takeLookTaskNo": "DK-2107292317452172",
//"takeLookUser": "管理员",
//"takeLookUserId": "1",
//"takePositionLatitude": null,
//"takePositionLongitude": null,
//"takeSignInStatus": 0,
//"takeSignInTime": null,
//"taskStatus": 0,
//"villageName": "中环一号一期 - 真北路4333弄"
data class LookTaskDetailRep(
//    var accompanyImgList:Double?,
//    var accompanyImgUrl:String?,
    var accompanyPositionLatitude:Double?,
    var accompanyPositionLongitude:Double?,
    var accompanySignInStatus:Int?,
    var accompanySignTime:String?,
    var accompanyUser:String?,
    var accompanyUserId:String?,
    var building:String?,
    var hNum:String?,
    var houseCode:String?,
    var houseId:String?,
    var id:String?,
    var latitude:Double?,
    var longitude:Double?,
//    var takeImgList:String?,
//    var takeImgUrl:String?,
    var takeLookTaskId:String?,
    var takeLookTaskNo:String?,
    var takeLookUser:String?,
    var takeLookUserId:String?,
    var takePositionLatitude:Double?,
    var takePositionLongitude:Double?,
    var takeSignInStatus:Int?,
//    var takeSignInTime:String?,
    var taskStatus:Int?,
    var villageName:String?
)